import { useState } from "react";
import type { FormEvent } from "react";
import { useAuth } from "./model/AuthContext";
import { useTrackerViewModel } from "./viewModels/useTrackerViewModel";
import type { Recurrence, TransactionType } from "./model/types";
import { PAYMENT_TYPES } from "./model/types";
import { localDateKey, occurrencesInRange, periodKey } from "./model/domain";

type Page = "dashboard" | "calendar" | "transactions" | "budgets" | "bills" | "maintenance" | "history";
const today = (): string => new Date().toISOString().slice(0, 10);
const currency = (value: number): string => `RM${value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/** Root view; page state and mutations remain in ViewModels and the Tracker model. */
export default function App() {
  const { user, loading: authLoading, sheetsAccessToken, configurationError, signIn, signOut } = useAuth();
  const vm = useTrackerViewModel(sheetsAccessToken);
  const [page, setPage] = useState<Page>("dashboard");
  const [sheetLink, setSheetLink] = useState("");
  const [initializing, setInitializing] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function connect(event: FormEvent) { event.preventDefault(); setInitializing(true); setActionError(null); try { await vm.connect(sheetLink, true); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Unable to connect sheet."); } finally { setInitializing(false); } }
  async function run(action: () => Promise<void>, confirmation?: string) { if (confirmation && !window.confirm(confirmation)) return; setBusy(true); setActionError(null); try { await action(); await vm.reload(); } catch (reason) { setActionError(reason instanceof Error ? reason.message : "Action failed."); } finally { setBusy(false); } }

  if (authLoading) return <main>Loading…</main>;
  if (configurationError && !vm.isDemo) return <main className="auth"><h1>Configure Firebase first</h1><p>{configurationError}</p><ol><li>Create <code>.env</code> from <code>.env.example</code>.</li><li>In Firebase Console, create a Web App and copy its configuration values.</li><li>Enable Authentication → Google sign-in.</li><li>Restart <code>npm run dev</code>.</li></ol></main>;
  if (!user && !vm.isDemo) return <main className="auth"><h1>PayTrack</h1><p>Your private Google Sheet is your database.</p><button onClick={() => void signIn()}>Sign in with Google</button></main>;
  if (!sheetsAccessToken && !vm.isDemo) return <main className="auth"><h1>Sheets access needed</h1><p>Sign in again and approve Google Sheets access to connect your private workbook.</p><button onClick={() => void signIn()}>Grant Sheets access</button><button className="secondary" onClick={() => void signOut()}>Sign out</button></main>;
  if (!vm.spreadsheetId && !vm.isDemo) return <main className="auth"><h1>Connect your private Sheet</h1><p>Create a blank Google Sheet owned by {user?.email}, paste its link below, then initialize its PayTrack tabs.</p><form onSubmit={connect}><input aria-label="Google Sheets link" value={sheetLink} onChange={(event) => setSheetLink(event.target.value)} placeholder="https://docs.google.com/spreadsheets/d/..." required /><button disabled={initializing}>{initializing ? "Initializing…" : "Connect and initialize"}</button></form>{actionError && <p className="error">{actionError}</p>}</main>;

  return <div className="shell"><aside><h1>PayTrack</h1>{(["dashboard", "calendar", "transactions", "budgets", "bills", "maintenance", "history"] as Page[]).map((item) => <button className={page === item ? "active" : ""} onClick={() => setPage(item)} key={item}>{item}</button>)}<small>{vm.isDemo ? "Local demo mode" : user?.email}</small>{!vm.isDemo && <><button className="secondary" onClick={vm.disconnect}>Disconnect sheet</button><button className="secondary" onClick={() => void signOut()}>Sign out</button></>}</aside><main>{vm.isDemo && <p className="demo">Demo mode: data is stored only in this browser. Set VITE_DEMO_MODE=false to use Firebase and Google Sheets.</p>}{actionError && <p className="error">{actionError}</p>}{(vm.loading || busy) && <p>{busy ? "Saving…" : "Loading…"}</p>}{vm.error && <p className="error">{vm.error}</p>}<fieldset disabled={busy}>{vm.data && <TrackerPage page={page} data={vm.data} run={run} tracker={vm.tracker!} />}</fieldset></main></div>;
}

function TrackerPage({ page, data, run, tracker }: { page: Page; data: NonNullable<ReturnType<typeof useTrackerViewModel>["data"]>; run: (action: () => Promise<void>, confirmation?: string) => Promise<void>; tracker: NonNullable<ReturnType<typeof useTrackerViewModel>["tracker"]> }) {
  if (page === "dashboard") return <Dashboard data={data} run={run} tracker={tracker} />;
  if (page === "calendar") return <Calendar data={data} />;
  if (page === "transactions") return <Transactions data={data} run={run} tracker={tracker} />;
  if (page === "budgets") return <Budgets data={data} run={run} tracker={tracker} />;
  if (page === "bills") return <Bills data={data} run={run} tracker={tracker} />;
  if (page === "maintenance") return <Maintenance data={data} run={run} tracker={tracker} />;
  return <History data={data} run={run} tracker={tracker} />;
}

function Dashboard({ data, run, tracker }: Props) { return <><h2>Dashboard — {data.dashboard.month}</h2><div className="stats"><Stat label="Income" value={data.dashboard.totalIncome}/><Stat label="Expense" value={data.dashboard.totalExpense}/><Stat label="Net" value={data.dashboard.netAmount}/></div><h3>Budgets</h3>{data.dashboard.budgets.map((budget) => <p key={budget.category}>{budget.category}: {currency(budget.spent)} / {currency(budget.monthlyLimit)}</p>)}<h3>Bills needing attention</h3>{data.bills.filter((bill) => bill.status === "overdue" || bill.status === "due_soon").map((bill) => <p key={bill.bill.id}>{bill.bill.name} — {bill.status} <button onClick={() => void run(() => tracker.markBillPaid(bill.bill.id))}>Mark paid</button></p>)}</> }
function Stat({ label, value }: { label: string; value: number }) { return <section><strong>{currency(value)}</strong><span>{label}</span></section>; }

type Props = { data: NonNullable<ReturnType<typeof useTrackerViewModel>["data"]>; run: (action: () => Promise<void>, confirmation?: string) => Promise<void>; tracker: NonNullable<ReturnType<typeof useTrackerViewModel>["tracker"]> };

function Transactions({ data, run, tracker }: Props) {
  const [date, setDate] = useState(today()); const [type, setType] = useState<TransactionType>("expense"); const [category, setCategory] = useState(""); const [amount, setAmount] = useState(""); const [description, setDescription] = useState(""); const [paymentType, setPaymentType] = useState(""); const [remarks, setRemarks] = useState(""); const [newCategory, setNewCategory] = useState("");
  return <><h2>Transactions</h2><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.addTransaction({ date, type, category, amount: Number(amount), description, paymentType, remarks })); setAmount(""); setDescription(""); setRemarks(""); }}><input type="date" value={date} onChange={(event) => setDate(event.target.value)} required/><select value={type} onChange={(event) => setType(event.target.value as TransactionType)}><option value="expense">Expense</option><option value="income">Income</option></select><select value={category} onChange={(event) => setCategory(event.target.value)} required><option value="">Category</option>{data.categories.filter((item) => item.type === type).map((item) => <option key={item.id}>{item.name}</option>)}</select><input type="number" min="0" step="0.01" placeholder="Amount" value={amount} onChange={(event) => setAmount(event.target.value)} required/><input placeholder="Description" value={description} onChange={(event) => setDescription(event.target.value)}/><select value={paymentType} onChange={(event) => setPaymentType(event.target.value)}><option value="">Payment type</option>{PAYMENT_TYPES.map((item) => <option key={item}>{item}</option>)}</select><input placeholder="Remarks" value={remarks} onChange={(event) => setRemarks(event.target.value)}/><button>Add</button></form><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.addCategory(newCategory, type)); setNewCategory(""); }}><input placeholder="New category" value={newCategory} onChange={(event) => setNewCategory(event.target.value)} required/><button>Add {type} category</button></form>{data.transactions.map((item) => <p key={item.id}>{item.date} · {item.category} · {currency(item.amount)} {item.paymentType && ` · ${item.paymentType}`} {item.remarks && ` · ${item.remarks}`} <button onClick={() => void run(() => tracker.deleteTransaction(item.id), "Delete this transaction permanently?")}>Delete</button></p>)}</>;
}

function Budgets({ data, run, tracker }: Props) {
  const [category, setCategory] = useState(""); const [limit, setLimit] = useState("");
  return <><h2>Budgets</h2><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.setBudget(category, Number(limit))); setLimit(""); }}><select value={category} onChange={(event) => setCategory(event.target.value)} required><option value="">Expense category</option>{data.categories.filter((item) => item.type === "expense").map((item) => <option key={item.id}>{item.name}</option>)}</select><input type="number" min="0" step="0.01" value={limit} onChange={(event) => setLimit(event.target.value)} placeholder="Monthly limit" required/><button>Save budget</button></form>{data.budgets.map((item) => <p key={item.id}>{item.category}: {currency(item.monthlyLimit)} <button onClick={() => void run(() => tracker.deleteBudget(item.id), "Delete this budget permanently?")}>Delete</button></p>)}</>;
}

function Bills({ data, run, tracker }: Props) {
  const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState(""); const [dueDay, setDueDay] = useState("1"); const [recurrence, setRecurrence] = useState<Recurrence>("monthly");
  const dueLabel = recurrence === "monthly" ? "Day of month" : recurrence === "weekly" ? "Day of week (1=Mon)" : "Day of year";
  return <><h2>Recurring bills</h2><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.addBill({ name, amount: Number(amount), category, dueDay: Number(dueDay), recurrence })); setName(""); setAmount(""); }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Bill name" required/><input type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Amount" required/><select value={category} onChange={(event) => setCategory(event.target.value)} required><option value="">Expense category</option>{data.categories.filter((item) => item.type === "expense").map((item) => <option key={item.id}>{item.name}</option>)}</select><select value={recurrence} onChange={(event) => setRecurrence(event.target.value as Recurrence)}><option value="monthly">Monthly</option><option value="weekly">Weekly</option><option value="yearly">Yearly</option></select><label>{dueLabel}<input type="number" min="1" max={recurrence === "weekly" ? 7 : recurrence === "yearly" ? 366 : 31} value={dueDay} onChange={(event) => setDueDay(event.target.value)} required/></label><button>Add bill</button></form>{data.bills.map((item) => <p key={item.bill.id}>{item.bill.name} · {currency(item.bill.amount)} · {item.bill.recurrence} · {item.status} {!item.isPaidForCurrentPeriod && <button onClick={() => void run(() => tracker.markBillPaid(item.bill.id))}>Mark paid</button>} <button onClick={() => void run(() => tracker.deleteBill(item.bill.id), "Delete this recurring bill permanently?")}>Delete</button></p>)}</>;
}

function Maintenance({ data, run, tracker }: Props) {
  const [mileage, setMileage] = useState(String(data.carInfo.currentMileage || "")); const [name, setName] = useState(""); const [notes, setNotes] = useState(""); const [months, setMonths] = useState(""); const [km, setKm] = useState(""); const [lastServiceDate, setLastServiceDate] = useState(today()); const [cost, setCost] = useState(""); const [costCategory, setCostCategory] = useState("");
  return <><h2>Car maintenance</h2><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.setMileage(Number(mileage))); }}><input type="number" min="0" value={mileage} onChange={(event) => setMileage(event.target.value)} placeholder="Current km" required/><button>Update mileage</button></form><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.addMaintenance({ name, notes, intervalMonths: Number(months) || 0, intervalKm: Number(km) || 0, lastServiceDate })); setName(""); setNotes(""); }}><input value={name} onChange={(event) => setName(event.target.value)} placeholder="Maintenance item" required/><input value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Notes"/><input type="number" min="0" value={months} onChange={(event) => setMonths(event.target.value)} placeholder="Months"/><input type="number" min="0" value={km} onChange={(event) => setKm(event.target.value)} placeholder="Kilometres"/><input type="date" value={lastServiceDate} onChange={(event) => setLastServiceDate(event.target.value)} required/><button>Add item</button></form><div className="inline-fields"><input type="number" min="0" step="0.01" value={cost} onChange={(event) => setCost(event.target.value)} placeholder="Completion cost (optional)"/><select value={costCategory} onChange={(event) => setCostCategory(event.target.value)}><option value="">Car Maintenance category</option>{data.categories.filter((item) => item.type === "expense").map((item) => <option key={item.id}>{item.name}</option>)}</select></div>{data.maintenance.map((item) => <p key={item.item.id}>{item.item.name} · {item.status} · {item.item.notes} <button onClick={() => void run(() => tracker.markMaintenanceDone(item.item.id, { cost: Number(cost) || undefined, category: costCategory || undefined }))}>Mark done</button> <button onClick={() => void run(() => tracker.deleteMaintenance(item.item.id), "Delete this maintenance item permanently?")}>Delete</button></p>)}</>;
}

function Calendar({ data }: { data: Props["data"] }) {
  const initial = new Date(); const [year, setYear] = useState(initial.getFullYear()); const [month, setMonth] = useState(initial.getMonth());
  const first = new Date(year, month, 1); const start = new Date(year, month, 1 - ((first.getDay() + 6) % 7)); const last = new Date(year, month + 1, 0); const end = new Date(year, month + 1, last.getDate() + (6 - ((last.getDay() + 6) % 7)));
  const events = new Map<string, { title: string; status: string }[]>(); const add = (date: string, title: string, status: string) => events.set(date, [...(events.get(date) ?? []), { title, status }]);
  for (const status of data.bills) for (const date of occurrencesInRange(status.bill.dueDay, status.bill.recurrence, start, end)) { const iso = localDateKey(date); const paid = status.bill.lastPaidPeriod === periodKey(date, status.bill.recurrence); const days = Math.round((date.getTime() - Date.now()) / 86_400_000); add(iso, status.bill.name, paid ? "paid" : days < 0 ? "overdue" : days <= 5 ? "due soon" : "upcoming"); }
  for (const status of data.maintenance) if (status.nextDueDate) add(status.nextDueDate, status.item.name, status.status.replace("_", " "));
  const days: Date[] = []; for (let cursor = new Date(start); cursor <= end; cursor = new Date(cursor.getFullYear(), cursor.getMonth(), cursor.getDate() + 1)) days.push(cursor);
  const move = (delta: number) => { const next = new Date(year, month + delta, 1); setYear(next.getFullYear()); setMonth(next.getMonth()); };
  return <><h2>Calendar</h2><div className="calendar-nav"><button onClick={() => move(-1)}>← Prev</button><strong>{first.toLocaleDateString(undefined, { month: "long", year: "numeric" })}</strong><button onClick={() => move(1)}>Next →</button></div><div className="calendar weekdays">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day) => <span key={day}>{day}</span>)}</div><div className="calendar">{days.map((day) => { const iso = localDateKey(day); return <div className={day.getMonth() === month ? "calendar-day" : "calendar-day muted"} key={iso}><strong>{day.getDate()}</strong>{(events.get(iso) ?? []).map((event, index) => <small className={`event ${event.status.replace(" ", "-")}`} key={`${event.title}-${index}`}>{event.title}</small>)}</div>; })}</div>{data.maintenance.filter((item) => item.item.intervalKm > 0 && item.item.intervalMonths === 0).length > 0 && <><h3>Mileage-only maintenance</h3>{data.maintenance.filter((item) => item.item.intervalKm > 0 && item.item.intervalMonths === 0).map((item) => <p key={item.item.id}>{item.item.name}: {item.kmUntilDue ?? 0} km remaining</p>)}</>}</>;
}

function History({ data, run, tracker }: Props) {
  const [date, setDate] = useState(today()); const [mileage, setMileage] = useState(""); const [description, setDescription] = useState("");
  return <><h2>Service history</h2><form onSubmit={(event) => { event.preventDefault(); void run(() => tracker.addServiceRecord(date, Number(mileage), description)); setMileage(""); setDescription(""); }}><input type="date" value={date} onChange={(event) => setDate(event.target.value)} required/><input type="number" min="0" value={mileage} onChange={(event) => setMileage(event.target.value)} placeholder="Odometer" required/><input value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Work done" required/><button>Add record</button></form>{data.serviceHistory.map((item) => <p key={item.id}>{item.date} · {item.mileage.toLocaleString()} km · {item.description} <button onClick={() => void run(() => tracker.deleteServiceRecord(item.id), "Delete this service record permanently?")}>Delete</button></p>)}</>;
}
